name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - name: Install test requirements
        run: pip install -r requirements-test.txt
      - name: Run tests
        env:
          PYTHONPATH: .:./rainmachine-developer-resources/sdk-parsers
          TEST_PURPLEAIR_API_KEY: ${{ secrets.TEST_PURPLEAIR_API_KEY }}
        run: python -m unittest discover -s ./test -t .
